global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

rule_files:
  - '/etc/prometheus/rules.yml'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['IP:PORT']
        labels:
          application: 'ktb-chat-backend'
          environment: 'production'

  - job_name: 'mongodb'
    static_configs:
      - targets: ['10.0.0.249:9216']
        labels:
          environment: 'production'

  - job_name: 'redis'
    static_configs:
      - targets: ['10.0.0.218:9121']
        labels:
          environment: 'production'

  - job_name: 'node-exporter'
    file_sd_configs:
      - files:
          - '/etc/prometheus/targets/node-exporters.prod.yml'
        refresh_interval: 5s
